### ISSUE TITLE
All health stations empty and not recharged

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#124]
I just noticed on the Dutch Fun server that in a CTL match (PadFridge) all HealthStations were completely out of power. The match had been going on for many, many hours without either team scoring a point. All stations were empty and were not recharged. I could enter the stations, but that did not change the condition. WoP seems to reach some strange states when a match runs for many hours... which is certainly not the normal use case.

**Comment by mgerhardy** [comment]
The server may not run longer than 24 days. This is known as the milliseconds would overflow after that time.

**Comment by mgerhardy** [comment]
overflow in `level.time` in `Think_ReloadStation`?

The max allowed runtime for a match/map in quake3 is round about 24 days. I suppose we could do something against this limit and increase it - but I also suppose that this is an edge case that is not worth to invest time in. The fix is trivial - but the testing might not.

**Comment by kai-li-wop** [comment]
No match should run for 24 days per map, so I also would keep it like it is. It is simply important to know, why this happens. I agree with you not to investigate further.
