### ISSUE TITLE
Map possibilitys

### ISSUE THREAD

**Issue by MancusNemo** [PadWorld-Entertainment/worldofpadman#131]
Why can I use the map Padgarden Night only in the Last Pad Standing and not the normal Padgarden Map as example. Can you pleas fix that and check if other Maps have the same issues?

**Comment by kai-li-wop** [comment]
Hi, this was done on purpose. Some maps or variants of maps, such as PadGarden night, were created specifically for LPS because the standard PadGarden map has some additional secret rooms (e.g. for the Imperius) where players can hide. PadGarden night does not contain these secret rooms. It is the same with some other maps of ENTE. It is up to the level designer which game type he wants to offer with his map. So it is not a mistake, it is a feature. ;) But you are welcome to start PadGarden and then switch to the game mode LPS. It is defacto possible to play PadGarden in LPS, even if it is not directly selectable via the menu.
