### ISSUE TITLE
LIBS: update SDL2 to 2.0.14

### ISSUE THREAD

**Issue by mgerhardy** [PadWorld-Entertainment/worldofpadman#144]
We should deliver an up-to-date libsdl2 with 1.6.1

**Comment by kai-li-wop** [comment]
To test this i guess I need to disable OpenAL, so the SDL audio driver is loaded. How can I verify the loaded SDL version in wop console? Is there a way?
Console gives as Sound Info: format audio_f32LSB, freq. 22050 ...
Shouldn't this be 44kHz? I remember we had 44kHz as default, or was this able with OpenAL only?
Also, I cannot remember why we removed the sound quality switch in the sound menu, but I think this would only work with SDL enabled, not with OpenAL. I am a little lost here.
Apart from my confusing questions I can hear the sound very fine and I don't see any issues with the SDL update right now on windows. ;)

**Comment by kai-li-wop** [comment]
OK, one issue. When the game is loading something in the UI, the sound starts to stutter a lot until loading is finished. It is enough to enter the player menu to reproduce it, or to grab the wop window while being in non-fullscreen mode and to move it around.

**Comment by mgerhardy** [comment]
That isn't the case with the old sdl version and openal disabled? Might be related to the sound buffer size - and the buffer running empty in the sound mixer thread. That will get a little bit ping pong as this is not reproducible here.

**Comment by kai-li-wop** [comment]
This is also noticeable with the old SDL version, but not as much as I think. But this is only a subjective impression. Furthermore, the old SDL audio specifications:
- Format: AUDIO_S16LSB
- Freq: 44100
- Samples: 1024
- Channels: 2 (surely only for my setup so identified, because of the existing stereo speakers)

**Comment by mgerhardy** [comment]
Does this prevent the merge? Otherwise I would like to push this into `master` because the build system changes rely on this.

**Comment by kai-li-wop** [comment]
I would say that we should at least provide the same SDL audio specifications in terms of quality (format, frequency, samples, etc.) as before, otherwise it would be a degradation of quality. For the buffer "problem", we should create a separate ticket, just not to forget about it.

**Comment by mgerhardy** [comment]
I've checked the history of `sdl_snd.c` - it always was 22khz - samples were `512` (if you switch to 44khz, you get `1024`), channels are and were `2`. The format was and is `AUDIO_S16SYS`, too.

**Comment by mgerhardy** [comment]
```
./wop/sounds/wop_player/paddybell/fall1.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
./wop/sound/pad_misc/fire1.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 8 bit, mono 44100 Hz
./wop/sound/kitchen/Bubbling.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
./wop/sound/kitchen/Toastump.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
./wop/sound/kitchen/Ovenplate.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
./wop/sound/kitchen/Microwave.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
./wop/sound/pad_animals/zirpen2.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
```

These are the only sound files with 44khz - everything else is 22khz or lower.

**Comment by kai-li-wop** [comment]
Ok, maybe I don't get it right. I simply applied and tested your changes and the console suddenly reported 22khz audio with SDL enabled. Also while playing the music from the juke box, the console complained about the music not being 22kHz (in fact it is 44kHz). So this appeared to me like a misconfiguration auf WoP's default sound values coming with your PR. Those are in WoP 1.6 in fact 44kHz with SDL enabled, like the console reports there correctly. I never changed this value manually to 44kHz, so it must have been set as default value somewhere, but not by me.
I know that Q3 had a menu option to switch between low and high quality, which is 11kHz and 22kHz imho. WoP does not have this option in the sound menu any more but has 44kHz as default and also a lot of 44kHz music and sound samples, which Quake3 doesn't have. Otherwise the 44kHz music for the player would not make any sense. Also console never complained about music not being 22kHz.
I simply want to make sure, that WoP 1.6.1 is not switching the sound back to 22kHz when 44kHz was set before. The user cannot set it easily without a menu option (we should put it back in with WoP 1.7).

**Comment by kai-li-wop** [comment]
You forgot about the ogg files.

**Comment by kai-li-wop** [comment]
WoP 1.2 fresh install with OpenAL disabled at high quality (22kHz). SDL was not implemented in this version I think. 
![grafik](https://user-images.githubusercontent.com/44040989/121301697-e1c28b80-c8f8-11eb-9790-9bf4e7dfc73e.png)

WoP 1.5.1 fresh install with OpenAL disabled. In fact, it had also 22kHz as default, when SDL enabled. Also the sound quality switch was in the sound menu providing "low" and "high" option, but I cannot see if it's working, since the sound info data in console is not changing.
![grafik](https://user-images.githubusercontent.com/44040989/121302906-ade86580-c8fa-11eb-8c59-c148d5f0ccbc.png)

WoP 1.6 fresh install with OpenAL disabled (SDL enabled) delivered 44kHz as default due to high quality music and sound samples as ogg files, which came with the patch. The sound quality switch in the sound menu is gone. I cannot remember exactly why we removed it, probably it was not working.
![grafik](https://user-images.githubusercontent.com/44040989/121303694-ad9c9a00-c8fb-11eb-84bf-dab8307f2c39.png)

WoP 1.6.1 beta with your SDL2 PR applied. Default here is 22kHz when SDL enabled, like already described.
![grafik](https://user-images.githubusercontent.com/44040989/121304397-96aa7780-c8fc-11eb-9aa3-d5881c6b4ea7.png)

ioQuake3 1.36 (some GIT version from 2018 I have installed) offers 3 sound quality option, when SDL enabled; "low", "medium" and "high" which is different to old WoP and Quake 3 versions. When switching, it in fact changes from 11kHz to 22kHz and to 44kHz. Also when SDL disabled, the quality option switch is disabled (grayed out) too. We should consider this approach with WoP 1.7.
![grafik](https://user-images.githubusercontent.com/44040989/121306477-2bae7000-c8ff-11eb-93c1-ed144878e7be.png)

I simply want to make sure, that WoP 1.6.1 has 44kHz enabled (16bit is enough since we don't have 32 bit sound samples in general). For the menu I will create another ticket.

**Comment by mgerhardy** [comment]
See here - https://github.com/PadWorld-Entertainment/worldofpadman/commit/3ac411c0cc0615483aedee0b59530e755b946d67

Was forgotten while I did the ioq3 merge. But the sound quality in wop is not related to the sdl2 version update. I agree with having this in the options menu would be a good thing.

**Comment by kai-li-wop** [comment]
Ah OK, then I was wrong connecting it with #145. To be honest, I was not checking 1.6.1 with SDL enabled without your PR, only WoP 1.6. Super, then I am happy. ;)
I leave it to you, if you want to take care about #150 for WoP 1.6.1 or if you want to leave it for WoP 1.7. Actually it is a bugfix regarding WoP 1.5.
