### ISSUE TITLE
Harm's Hütte - item placement improvement

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#173]
Some time ago blu took a closer look at the item placement of Harm's Hütte, focusing on the Splasher position, which he thinks is over powered. The suggestion is basically to swap Betty and Splasher. See https://www.moddb.com/groups/padcommunity/forum/thread/map-harms-huette#1091837

ToDo:
- [x] Swap Betty and Splasher
- [x] Move weapon spawn a little distant from health station on the desk
- [x] Place 5 PadShards on the chair

**Comment by 3aTmE** [comment]
Just played a local game with bots. 

The PadShards on the Chair is an very welcome addition.
Giving it an purpose instead of being simply and obstacle.

Also the Splasher is now far easier to get and very much harder to defend. 
Same with the old position which is also hard to defend since the Betty spawns there.

Even with bots the changes were quite noticeable! 

Can't wait to play with other players and see how the map plays with human opponents.
