### ISSUE TITLE
 Glowstar's ColorStage - player route fixes / improvements

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#174]
Some time ago blu took a closer look at the route possibilities in Glowstar's ColorStage and mentioned some fixes and room for improvement. This basically concentrates on probably unwanted routes (see screenshots).

Shortcut directly to the lolly
![shot0025_edited](https://user-images.githubusercontent.com/44040989/179483922-78680662-a774-47a3-a7f0-cf8d6f0898ee.jpg)

Shortcut between wall and glass barrier:
![shot0026_edited](https://user-images.githubusercontent.com/44040989/179483998-2401c8e4-6fb2-4ffd-b70e-1cc4086b41f8.jpg)

Teleporter confusion by switching platform sides and direction of player view
![shot0028_edited](https://user-images.githubusercontent.com/44040989/179484223-73e7b7c1-4313-404a-9f14-e62b39d3c636.jpg)

ToDo:
- [x] Extend the wall between lolly and platform and bring more distance between the outer and inner base platforms to make it more difficult to directly jump to the lolly
- [x] Extend the glass wall to cover the whole side of the platform and add player clip brushes
- [x] Teleporter dest should be behind the weapon at platform edge so players can see and collect the weapons, move weapons more in direction of platform center, away from the edge

**Comment by kai-li-wop** [comment]
The teleporter consists of a trigger brush and two targets that are randomly selected. The problem is that at each destination the player is put in different angles of view, which leads to confusion. I will change the angle and position so that the player always faces the PadShield, whether teleported to the left or right side of the upper platform.

**Comment by kai-li-wop** [comment]
With 0f4cd7af744232a88f76647483e7195f96250f95 the map received further updates and changes. Here is a (complete) list:
- remove ambient light key and replace with gamma set to 1.2
- better quality light map by setting samplesize to 8 and dirtscale to 2 etc.
- skybox diffuse light emission increased from 90 to 150 to bring more light into the map
- should fix all shader and BSP validation warnings
- moved blue/red lolly bases further away from map center and shifted wall closer to jump pad to make it harder to weapon jump directly from upper platforms to lolly bases
- extend health station platform and move Splasher there from the lolly platform
- extend glass wall on upper platform to make weapon jump to platform with BubbleG impossible
- slight adjustment of lolly position behind the column and further away from spawn points
- move spawn points and health stations further to the edge so they are no longer in the way
- adjust teleporter destinations to avoid confusion; the player now always faces the PadShield and always has Betty/Pumper in front of him; these weapons needed to be moved towards the PadShield
- placed a few more PadShards around the PadShields
- removed all Boaster ammo, since Boaster is not present on this map
- repositioned ammo bottles in general; reduced Balloony/Betty ammo from 6 to 4; increased Splasher ammo from 4 to 6
- prepares the map for 1LCTL by adding a neutral lolly at the REViVAL position; adds 2 new REViVALs on the lower platforms near the columns in 1LCTL only; REViVAL position in CTL remains untouched

**Comment by 3aTmE** [comment]
I took a little bit of Time to check the changes made: 

## What was tested ?
- Teleporter on Both bases 
- That changes in the Geometry (Larger Platforms, Lolly position) are same on both bases
- Trying to , easily, Weapon jump from the Fence to the Bubble G. ( you can still reach the Plattform by jumping on the Wall but it's been made hard enough that you just simply don't have any advantage by doing so. )
- Checking if changes in the Item placement also occurs on both bases.
- Checking if the most common ways to score Quickly is still possible (It very is)

I've recorded a bit of footage regarding being able to score, too,  quickly :

https://youtu.be/5K-DXtdrGaU ( Jumping base 2 base /w weaponjump )

 https://youtu.be/LQm6cnD7Fn0 ( Jumping from the upper Plattform to the lolly with and without weaponjumps )
 
 This might be impossible to fix without changing the layout of the map completely tho.

## What was not tested? 
- 1 Lolly CTL and the changes in the Item placement

## Everything else? 

**Works like it should! Found no other issues than those i've recorded / mentioned!**

**Comment by kai-li-wop** [comment]
The only solutions I can think of might be to find a way to build a barrier that can only be entered from one side, or to move the outer lolly bases far enough away from the center so that any Betty jump ends up in the pit. Btw I never have imagined those weapon jumps possible. This is worse that blu described. ;)

**Comment by kai-li-wop** [comment]
@3aTmE: What about switching lolly and bubbleg positions in each team base. This is not preventing weapon jumps in the way shown like in the videos, but you still have a longer way to the lolly if you do so. I would remove the lower jump pad leading to the bubbleg platform and move it to reach the current lolly platform on the other side.

**Comment by 3aTmE** [comment]
> @3aTmE: What about switching lolly and bubbleg positions in each team base. This is not preventing weapon jumps in the way shown like in the videos, but you still have a longer way to the lolly if you do so. I would remove the lower jump pad leading to the bubbleg platform and move it to reach the current lolly platform on the other side.

@kai-li-wop i tried 2 different approaches to fix this issue.

First by mirroring the Bases (and fixing the jump pads) and second, like you recommended by changing the positions of the lolly with the BubbleG.

I created a small Gameplay video showcasing both approaches, with weapon jumps and without :
https://youtu.be/lLLX7nZnLVc 
(pardon the awful looking textures. I did not bother to fix the mess caused by the de-compiling)

I would probably go with the second approach. 
Removing the lower jump pad to the BubbleG won't help against unfair / fast scoring on this map (in the video i haven't used this jump pad at all). 

But the switch of the items alone helped to made it harder. 
Especially when trying to get the lolly fast without any weapon jumps (your jumps must be really, precise. Skilled players might be still able to pull it off reliably ) 

It's also way less work to implement :)

I'm not sure if there is a good way to prevent fast scoring on this map entirely, since it is such a open space.

**Comment by kai-li-wop** [comment]
@3aTmE: When I see all of this my only and probably best solution would be to move all lolly bases far more away from the middle bases, minimum 1500 or more units. Would be good to find out how much units would be necessary. Also I would add a player clip at the map's ceiling to prevent people to reach the upper bars and to weapon jump from there.

**Comment by 3aTmE** [comment]
> @3aTmE: When I see all of this my only and probably best solution would be to move all lolly bases far more away from the middle bases, minimum 1500 or more units. Would be good to find out how much units would be necessary. Also I would add a player clip at the map's ceiling to prevent people to reach the upper bars and to weapon jump from there.

that could work. I'll test it later with a playerclip on the columns risen to the skybox and the bases way more further away. I would go probably with at least 2000 units since skilled players could  easily overcome an 1500 gap. Maybe even further :) 

I hope it won't change that much how the map plays. It would also remove the possibility to jump from the lower platforms to their respective base. But i guess it is a good trade when the rest of the map can't be exploited so easily instead.

**Comment by 3aTmE** [comment]
@kai-li-wop I guess moving the bases further away is the best approach!

I tried 2 different distances (1500 units and 2500 units) and at 2500 you can't cheese your way to the enemy the base by weapon / strafe  Jumping anymore! 

Recorded a bit of Game Play to show the changes made. 
Also by moving bases further away you also remove the issue with the ceiling since the distance is too great anyways. (But just to be sure i player clipped it)

But like i said, the path from the splasher to the lower Plattform won't work anymore.

Anyways, here the vid : https://youtu.be/9IuKhf5PEcM

**Comment by kai-li-wop** [comment]
Hope this helps to bring all those issues to an end. a503b1726ed0fc78def5f149dcee298b49d6d4c1

**Comment by 3aTmE** [comment]
Just tested it! It's definitely not possible to use the old routes anymore.

I can confirm this fix.
