### ISSUE TITLE
Personal player scores in BB should take awards into account

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#220]
A player's personal scores should now take into account the various awards in Big Balloon. The current situation is that a player only receives one personal point for capturing a balloon. Similar to Capture the Lolly, this should be more differentiated, taking PadHero and PadAce into account. Destroying an opponent's balloon is also not yet rewarded. Based on CTL, it could look like this:

- [x] BB_CAPTURE_BONUS 5 // what you get for capturing a balloon
- [x] BB_COUNTER_BONUS 1 // what you get for countering a balloon
- [x] BB_DEFENSE_BONUS 1 // what you get for defending a balloon (PadHero)
- [x] BB_ASSIST_BONUS 2 // what you get for assisting in capturing a balloon (PadAce)

**Comment by kai-li-wop** [comment]
Implemented with ef4430502c34f525b87ef2f7193d98d3a9db891d and f77251c9b6d2b0d20e7141eb51aff6f23b2b3c4c

**Comment by 3aTmE** [comment]
Just tried it. The points are given like they are supposed to.  👍 

### What was tested?
Checking if the points are given under the right circumstances and in the correct amount:
✅ Getting 5 Points for capturing a Balloon 
✅ Getting 1 Point for defending a Balloon  
✅ Getting 1 Point for destroying a enemy Ballon 
✅ Getting 2 Points for assisting in Capturing ( was way harder to accomplish since i needed to use 2 Clients to pull it off. The bots didn't want to help as much as i hope they would ;) )
