### ISSUE TITLE
Prevent players from abusing the extra health and armor in CATCH

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#221]
A problem for the balancing in the CATCH game mode could be that the player who has picked up the killer duck can recharge health and armor too easily by simply throwing the killer duck directly at his own feet and then picking it up again straight away. To prevent this, a lockout timer should be integrated that blocks this feature if the same player picks up the killer duck again within 5(?) seconds. The timer should be reset to the lock time with each pick-up. The lock time should not be active when a carrier change takes place, so the new owner gains full health and armor again one time.

**Comment by kai-li-wop** [comment]
Probably a better solution would be to completely forbid that the player can pick the killerduck directly after he lost it. So someone else needs to hold and lose it before he can pick it up again. Then we don't need to implement a timer, just a flag who was the last carrier.

**Comment by mgerhardy** [comment]
This is now implemented for the player and the bots (they couldn't drop the killerducks until now, because they instantly recollected them - even though they are never dropping them anyway)

**Comment by kai-li-wop** [comment]
@mgerhardy: Looks good to me. Not sure about the set time limit, but we will wait for the feedback of the players if adjustments are necessary here. Maybe an info message would be useful, if a player wants to collect it directly after he dropped it.
"You can't pick up the KillerDuck for a while!"

For example, there is also a message in syc ffa when you try to collect your own cartridge, which is not possible.
"You can't grab your own cartridge!"

**Comment by 3aTmE** [comment]
Okay, i just tried to check this feature on the recent dev version and the Feature _itself_ worked as intended.

The thing is : i could pick up Armor and recharge my Health just fine _while_ holding the Killer Duck.
Even picking up Power-Ups like Revival and PadPower worked!  ( Getting hold of the Floater while holding the Killer Duck did not work ) 

Is this intentional?  

I was still unable to pick up any Ammunition and Weapons tho. 

**What was Tested?**
- Starting a local CATCH game with bots
- getting the KillerDuck
- Throwing the KillerDuck away, trying to collect items and then re-collect the KillerDuck -> Was not able to, got a message instead! Works as intended! ✅ 
- Trying picking up Armor, Powerups and recharge Health while holding the KillerDuck -> Was able to. Is this behaviour intended?

**Comment by kai-li-wop** [comment]
For now it is intended that you can't pick up weapons, ammo and holdables while holding the Killerduck. Usually hunters are following the Killerduck carrier and cannot recollect weapons and ammo, if the Killerduck carrier is picking them up short before. They would run out of ammo fast.

Killerduck carrier won't have time to recharge health, so health stations are not a good choice. So we don't really need them. To collect shield is ok I think and hunters don't need it.

Powerups are ok to be used when picking up the Killerduck I think.

But in the end we will see how the game mode will work. Until now there were no complaints about the balance. So I hope on more feedback about where it feels imbalanced. So use the beta test time still available. 😉

**Comment by cinnamon189** [comment]
If carriers can hide for a while, they can drop the KillerDuck, camp on it for a few seconds and pick it up before it respawns. Could be seen as a reward for finding a good hideout, but feels more like an exploit to me. Especially if there are not many human players, so that the carriers will repeatedly get opportunities like that. In short, I think the KillerDuck should respawn before the former carrier can just pick it up again.

**Comment by kai-li-wop** [comment]
One solution could be to extend the lockout time beyond the respawn time.
