### ISSUE TITLE
PK3: automate pk3 creating from assets files.

### ISSUE THREAD

**Issue by mgerhardy** [PadWorld-Entertainment/worldofpadman#24]
We have to define the new pk3 layout. We did it like this: https://github.com/ufoai/ufoai/blob/master/build/data.mk in ufoai - maybe this would be helpful.

**Comment by robo9k** [comment]
Please also consider creating a deterministic .zip aka .pk3 so the build is reproducible

**Comment by kai-li-wop** [comment]
For v1.6.1 I would like to suggest/see a temporary intermediate way. If we repackage all the content into new pk3 files with different filenames, people will have to download all the content. There will probably be some breaks with existing installations. Also, I don't see much point in shipping all the old stuff again when there will probably be a sweeping rewrite and reorganization of the for WoP v1.7. WoP v1.6.1 should ship as a patch and full release, as discussed in the WoP team meeting.

The goal for WoP 1.6.1 must be to create a single wop_007.pk3 that includes at least the assets changes. So we need to pack it based on the diff of the original commit and the last commit of the wop assets folder in the assets repository. If it is not possible to include the new QVMs in wop_007.pk3 due to the different repositories of code and assets, I would suggest here to create a new wop_008.pk3 just for the QVMs. This will not break anything.

Then for WoP v1.7, we are welcome to have a different approach and we will be completely free there as well. There will be only one full version and we can also break existing installations. But I don't want that now with WoP v1.6.1, which should remain compatible with existing WoP v1.6 installations.

**Comment by mgerhardy** [comment]
I've implemented this in wop-data now. See the attached pipelines and the resulting artifacts. Closing this for now.

**Comment by mgerhardy** [comment]
Fixed issue with subdirs and multiple identical files if you changed them more than once
