### ISSUE TITLE
Crosshair for 3rd person mode

### ISSUE THREAD

**Issue by simse15** [PadWorld-Entertainment/worldofpadman#292]
So i hoped that the crosshair would be finally added to 3rd person mode finally but sadly it didn´t. is there a chance u can add that in so people can properly play in 3rd person mode at some point. its just my thought on it since 3rd person is in the game :)

**Comment by mgerhardy** [comment]
Not sure if this is what we are looking for, too:

* https://github.com/LegendaryGuard/BFP/commit/48ba85f026ff110c740581eb036b5be8de63e8d8
* https://github.com/LegendaryGuard/BFP/commit/a80f5a3f51e4eb09df9f614deaf8afe594943eab

**Comment by kai-li-wop** [comment]
This feature is already mentioned here #9. I would like to have this implemented but I don't know how. If somebody would like to spend time on this I would be happy. I am also not sure if we can simply take the code from BFP since this is licensed differently with GPL 3.0. I will close this issue and please refer to the other ticket for further implementation. I will put it back on the todo list.
