### ISSUE TITLE
Nested ZIP distribution is confusing if using a ZIP extractor that always creates subfolders

### ISSUE THREAD

**Issue by Calinou** [PadWorld-Entertainment/worldofpadman#295]
When you extract the 1.7.0-beta1 ZIP, you find several ZIPs contained within, one for each operating system.

If you extract the ZIP using Windows' default utility or any other utility that always creates a subfolder, the resulting files will not be runnable because they are in the wrong folder:

![image](https://github.com/user-attachments/assets/2dd4ae05-bdbf-4433-a0b7-0cc134091d4a)

Checking for files in the parent directory won't suffice, because the native libraries in the `wop` folder won't be in the correct location.

To simplify installation, I suggest having everything extracted in the ZIP beforehand, similar to Xonotic's distribution.

**Comment by kai-li-wop** [comment]
That's a good hint. The zip files were due to win32 and win64 support which contain SDL2.dll in 32 and 64 bits but with the same name. So it is impossible to send it already extracted in the root folder, without overwriting one of those files. Additionally I needed to pack the beta version on a windows computer so when I extract the linux binaries into the root folder they lose the executable bit. That's why we released the beta with zip files containing the binaries. For the official release we won't do it that way and provide only 64bit binaries already extracted. So I mark this as done for now.
