### ISSUE TITLE
Speedy powerup causes excessive FOV on widescreen displays if `cg_fovAspectAdjust 1` is used

### ISSUE THREAD

**Issue by Calinou** [PadWorld-Entertainment/worldofpadman#298]
On 1.7.0-beta1, the FOV change that applies when running with the Speedy powerup is much higher since the FOV is now adjusted for widescreen displays automatically.

https://github.com/user-attachments/assets/df5b700b-a781-48f5-8d14-b438a75fe6d9

This is especially true if you increase `cg_fov` above its default, e.g. `cg_fov 105` on 16:9:

https://github.com/user-attachments/assets/599c0e2e-8adb-4e33-8172-e6cadeaba2ee

Conversely, if you use a lower-than-default FOV, the FOV change appears much more subtle. Example with `cg_fov 60`:

https://github.com/user-attachments/assets/be1faa2d-1fc1-48e6-8c47-7e61c442e300

To resolve this, the FOV offset needs to be changed from a fixed value to a dynamic value depending on the current FOV, with higher base FOV values warranting a *lower* FOV difference to keep the effect similar. I believe the same formula used for widescreen adjustment (or mouse sensitivity adjustment based on scoped weapon FOV) can be used here.

**Comment by kai-li-wop** [comment]
I can confirm the fix, but the Speedy FOV effect is now basically completely gone in super widescreen. I tested with 2560x720 (32:9) resolution and there was no visible Speedy FOV effect compared to 1280x720 (16:9) where it is still visible. But at 1680x720 (21:9), which should be our maximum supported widescreen aspect ratio, it is still visible, but weak. In general, however, the fix gives super-widescreen players an advantage by reducing the distortion of the Speedy FOV effect.

**Comment by kai-li-wop** [comment]
I think I found a good solution for this. The speedy factor usually is 1.5 but designed for 4:3 aspect ratio. With new wide screen aspect ratios like they are used today the speedy effect is to intense and due to auto fov correction it is even stronger, so like suggested the speedy factor of 1.5 needs to be dynamic.

If we devide it into some constant base and dynamic peak part I would to it like this: 1.0 + 0.5. So let's make 0.5 dynamic by aspect ration of the current screen --> factor = height / width.

| Height | Width | Factor | Base | Peak | Result
| ------ | ------ | ------ | ------ | ------ | ------
| 5 | 4 | 0,80 | 0.50 | 0.40 | 1.4
| 4 | 3 | 0.75 | 0.50 | 0.38 | 1.38
| 16 | 10 | 0.63 | 0.50 | 0.31 | 1.31
| 16 | 9 | 0.56 | 0.50 | 0.28 | 1.28
| 21 | 9 | 0.43 | 0.50 | 0.21 | 1.21


In the end the speedy factor is calculated this way: 

speedy factor = 1.0f + base * height / width

In my tests this worked pretty well.

**Comment by kai-li-wop** [comment]
A few screenshots of the result in different aspect ratios with and without speedy fov effect. Experience nearly stays the same in all aspect ratios.

32:9
![Image](https://github.com/user-attachments/assets/c2d482c6-8180-4297-8e7f-67c366652890)
![Image](https://github.com/user-attachments/assets/3e63382c-91c6-44df-8f3e-7e970a6bfc0e)

21:9
![Image](https://github.com/user-attachments/assets/89a12391-3944-4c2e-9c9f-c5fa923095da)
![Image](https://github.com/user-attachments/assets/47afc161-4d4c-42c9-a906-813f0017259f)

16:9
![Image](https://github.com/user-attachments/assets/90af3460-816d-454f-b1b1-205fb4116a23)
![Image](https://github.com/user-attachments/assets/2f60fff5-95fd-4ed4-86ad-e7480357a480)

16:10
![Image](https://github.com/user-attachments/assets/69f52cfc-b1ae-4a09-ad38-cdf6ac21b1ea)
![Image](https://github.com/user-attachments/assets/2f08b66c-9e63-4b56-803b-a345b550af29)

4:3
![Image](https://github.com/user-attachments/assets/c420e18a-494e-4bd2-868e-d30d97059218)
![Image](https://github.com/user-attachments/assets/7237be4f-4253-4486-a51e-14447770a121)

5:4
![Image](https://github.com/user-attachments/assets/15e51771-e515-40b4-930b-e7dd266d60fb)
![Image](https://github.com/user-attachments/assets/2942efa0-a185-41de-b664-2d8c5209f093)

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed. At least for 16:9 and 16:10 resolutions since my screens only have these aspect ratios.
