### ISSUE TITLE
Boaster will sometimes only play the looping sound, and not the initial firing sound

### ISSUE THREAD

**Issue by ninjakitty844** [PadWorld-Entertainment/worldofpadman#303]
There is a sound that only plays once when you **start** using the boaster. This is separate from the looping sound that constantly loops while using the boaster.

But this initial firing sound will **not** play if you are firing with a different weapon and then switch to boaster.

For example, hold the bubble g, and hold down your firing button. Then without releasing the firing button, switch to boaster. You will only hear the looping sound, and not the initial firing sound.

**Comment by kai-li-wop** [comment]
I can approve this behaviour which seems to be a bug.

**Comment by kai-li-wop** [comment]
As I can see from the code, it is necessary to press the fire button first to play the boaster flash sound once. This sound should only be played once, so the boaster sounds are handled differently than the sounds of other weapons. If there is no button press as described in your scenario, the sound will not play. Also, the scenario you describe is not a normal use case.

**Comment by ninjakitty844** [comment]
I noticed the bug in normal gameplay against bots, I was not intentionally doing anything weird. I would expect that starting to use the boaster should trigger the sound whether you were using a different weapon previously or not.

**Comment by kai-li-wop** [comment]
I understand that, but you wrote that you switched from another weapon to Boaster while holding down the fire button. That is not the normal use case. Usually you fire a weapon, release the button, switch to another weapon, and press the button again to fire. The code for Boaster is based on the lightning gun from Quake 3 Arena ... it is basically the same. So I tested it in ioquake3 and the behavior is the same. The initial flash sound (thunder) is missing in your use case when you switch to lightning gun while holding down the fire button. The code simply expects the fire button to be pressed after switching to lightning gun to play the initial flash sound. So it is intentional, not a bug as far as I can see.

**Comment by ninjakitty844** [comment]
I don't think this is intended behavior, because to me intentional means that someone wanted it to be this way, and would have said no if someone else volunteered to fix it.

That said, it's not important so I can understand not fixing it 👍
