### ISSUE TITLE
Outdated URL in Esc menu

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#324]
It says there that players should visit worldofpadman.com , when the current URL is worldofpadman.net.

**Comment by kai-li-wop** [comment]
The official valid web url is http://worldofpadman.com/. Since I am hosting and maintaining the official website ENTE and I agreed that it is much easier to do it from another domain https://worldofpadman.net/, where I have full access to. This is related to necessary ssl certificates and domain record entries (e.g. for the master server) which ENTE cannot provide. So the com domain is still the official while the net domain helps to host and maintain the website and other services. worldofpadman.com in fact leads to worldofpadman.net.
