### ISSUE TITLE
Hard Link, can'f find config

### ISSUE THREAD

**Issue by MancusNemo** [PadWorld-Entertainment/worldofpadman#326]
Hello,

when I try to install the game in /opt in Linux Mint it didn't work and it says can't find config.
Then I copied it to my home directory and than it works.

Please fix it. It looks like there is something hard linked.

greatings

**Comment by kai-li-wop** [comment]
Can you please give more information about the config you are talking about? Is it the default.cfg? This config is expected in the wop subdirectory of your installation directory and is part of the universal zip. When WoP is started for the first time, a user config is created from this default config in your linux user folder. WoP needs the default.cfg for the first start, otherwise it won't start.

**Comment by mgerhardy** [comment]
please also post the console logs

**Comment by kai-li-wop** [comment]
@MancusNemo: Without any additional information I will close this as won't fix soon.
