### ISSUE TITLE
1LC: Bot escorts camp once you drop the Lolly

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#328]
If you get the Lolly in 1LC, then try to hand it to a teammate, your bot escorts will camp until someone picks up the Lolly.

**Comment by kai-li-wop** [comment]
I think this is desired behavior. The bots try to protect the lolly carrier in 1LC. If the lolly carrier drops the lolly, they still protect it so the other team cannot pick it up. The question is, if the bots don't pick it up at all, @cinnamon189? They should pick it up to continue on to the enemy base. Maybe you can give some more details here. thanks

**Comment by cinnamon189** [comment]
Apparently, it depends on the bot: After you drop the Lolly, an escorting Padilla will just camp until another teammate picks up the Lolly. I have not tested yet whether she would fight opponents. An escorting Pad-RA and MonsterPad, on the other hand, will set themselves in motion as soon as you drop the Lolly - sometimes they go directly for it, sometimes they run around for a few seconds for no apparent reason and only then pick up the Lolly. Maybe rename this issue to something like "Bot escorts behave strangely if you drop the Lolly"? In any case, it may take a few days until I have tested this with all bots, unless someone would like to help me.

**Comment by kai-li-wop** [comment]
I just did a bit of testing myself and could not find any problems. When I drop the lolly near my bot escort, someone always picks it up. The bots all have the same characteristics, so it is quite random who picks it up and who stays in the escort. One thing I have noticed is that bots that are too far away from the lolly carrier will sometimes stand and camp because they cannot see and locate the lolly carrier when they are supposed to be escorting and protecting. This can happen on maps with blocked lines of sight like FrideWars. Other than that, I don't see anything we need to fix right now.
