### ISSUE TITLE
FREEZETAG: "you froze [yourself]"

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#335]
If you and another player (bot?) freeze each other at about the same time, there will appear a message saying that you froze yourself (where "yourself" will be replaced by your nick). This one has appeared twice within the same match, so I'm reasonably sure it's reproducible.

**Comment by kai-li-wop** [comment]
What happens when you really freeze yourself? Exactly what you described. I don't think it matters if a bot is nearby. It can happen that you freeze the bot and yourself from splash damage, like from Betty. That can happen. In any case, the game will say that you froze a player with your name instead of "you froze yourself", which is kind of wired.

![Image](https://github.com/user-attachments/assets/0adfc285-06cf-428e-b315-b28364780460)

**Comment by kai-li-wop** [comment]
Should be "fixed". I cannot use gender related strings in this case like himself, herself, itself so I "invented" "Self-freezing". ;)

![Image](https://github.com/user-attachments/assets/e22dc111-e502-437e-9cf2-17699357e1c0)

**Comment by cinnamon189** [comment]
Sounds good :)

To verify that I really had a case of unnoticed self-freezing, I would need some assistance. But, considering how minor this issue would be, I think we can just play regularly and see if it ever turns up again.
